### ISSUE TITLE
频繁读取数据，线程数飙升，CPU100%，然后就挂了

### ISSUE THREAD

**Issue by wangx036** [leogle/OPCAutomationDotNet#1]
请问有么有释放线程的操作？
opcServer.Disconnect() 释放连接时不会清线程吗？

我每次读取一个tag，都会Init一个client，读完就Disconnect，和频繁开关是不是也有关系？

希望能得到解答，谢谢

**Comment by wangx036** [comment]
用的是 MatrikonOPCSimulation

**Comment by wangx036** [comment]
经初步测试，基本可以确定是频繁开关连接导致。

**Comment by leogle** [comment]
建议不要频繁读取，通过客户端OpcDataChangedEvent事件获取标签变化。
基本逻辑是启动时去读一边，并添加监视，opc标签有变化时会推送事件
